server:
  port: ${PORT:8761}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:8762/eureka,http://peer2:8763/eureka,http://peer3:8764/eureka

---
spring:
  profiles: host1
server:
  port: 8762
eureka:
  instance:
    hostname: peer1
---
spring:
  profiles: host2
server:
  port: 8763
eureka:
  instance:
    hostname: peer2
---
spring:
  profiles: host3
server:
  port: 8764
eureka:
  instance:
    hostname: peer3
