eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8761}/eureka/
  instance:
    preferIpAddress: true
server:
  port: ${PORT:8081}
spring:
  profiles:
    active: ${PROFILE:dev}
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      atlas:
        uri: http://localhost:7101/api/v1/publish
